env:
  node: true
  es2020: true
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:prettier/recommended
plugins:
  - prettier
rules:
  prettier/prettier: error
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle:
    - 2
    - allow:
        - __filename
        - __dirname
parserOptions:
  ecmaVersion: latest
  sourceType: module
